### ISSUE TITLE
wifi errors

### ISSUE THREAD

**Issue by RobertoWa** [8890q/android_kernel_samsung_universal8890#1]
hello,

my system:

samsung s7 g930f
lineageos 18.1 (microg)

my issue:

logcat tells me a lot of error messages (#1) every second. only happens, when wifi is enabled (#2).

there is no such an issue on lineageos 17.1.

possible to fix that?

#
#1 error messages:
#
[3:dhd_rpm_state_t: 2368] exynos-pcie 15660000.pcie0: received Enter_L23_READY DLLP packet

[2:dhd_rpm_state_t: 2368] exynos-pcie 15660000.pcie0: ack message is ok

[2:dhd_rpm_state_t: 2368] exynos-pcie 15660000.pcie0: pcie clk enable, ret value = 0

[2:dhd_rpm_state_t: 2368] exynos-pcie 15660000.pcie0: l1ss disabled(0x8)

[1:dhd_rpm_state_t: 2368] exynos-pcie 15660000.pcie0: pcie clk enable, ret value = 0

#
#2 error when wifi starts:
#
05-21 17:06:13.722 I/android.hardware.wifi@1.0-service(3878): Wifi HAL started
05-21 17:06:13.723 I/WifiVendorHal(4135): Vendor Hal started successfully
05-21 17:06:13.725 I/WifiP2pNative(4135): Registering for interface available listener
05-21 17:06:12.630 I/        (0): [1:wifi@1.0-servic: 3878] ------------------------------------------------
05-21 17:06:12.630 I/        (0): [1:wifi@1.0-servic: 3878] ------------------------------------------------
05-21 17:06:12.630 I/        (0): [1:wifi@1.0-servic: 3878] dhd_wlan_power Enter: power on
05-21 17:06:12.631 E/        (0): [5:wifi@1.0-servic: 3878] exynos-pcie 15660000.pcie0: pcie clk enable, ret value = 0
05-21 17:06:12.651 E/        (0): [2:wifi@1.0-servic: 3878] exynos-pcie 15660000.pcie0: phy clk enable, ret value = 0
05-21 17:06:12.663 E/        (0): [2:wifi@1.0-servic: 3878] exynos-pcie 15660000.pcie0: l1ss disabled(0x8)
05-21 17:06:14.447 I/WifiHAL (3878): Initializing wifi
05-21 17:06:14.447 E/WifiHAL (3878): --- HAL version: 1.44.22.3 (r793775) ---
05-21 17:06:14.447 I/WifiHAL (3878): Creating socket
05-21 17:06:14.449 I/WifiHAL (3878): Initialized Wifi HAL Successfully; vendor cmd = 103
05-21 17:06:14.449 I/WifiHAL (3878): found interface wlan0
05-21 17:06:14.449 I/EthernetTracker(4135): interfaceLinkStateChanged, iface: wlan0, up: true
05-21 17:06:14.449 E/WifiHAL (3878): Calling Hal_init
05-21 17:06:14.449 E/WifiHAL (3878): Start Set Hal
05-21 17:06:14.450 D/WifiHAL (3878): error code -95 mapped to -3
05-21 17:06:14.450 E/WifiHAL (3878): Failed to register set hal start response; result = -3
05-21 17:06:14.450 E/WifiHAL (3878): wifi_start_hal failed

#end of message

**Comment by Exodusnick** [comment]
Here is still screenshot where with that was determined.
![IMG_20210522_114917_609](https://user-images.githubusercontent.com/24758741/119222390-7acd6600-baf4-11eb-8403-7d988302113b.jpg)
From RobertoWa.

**Comment by fcuzzocrea** [comment]
Those are not errors, are just debug output from the kernel of  the pci driver https://github.com/8890q/android_kernel_samsung_universal8890/blob/61c38a534543a5929ef214b4c319c577a2a6196e/drivers/pci/host/pci-exynos.c

**Comment by RobertoWa** [comment]
ok, thank u very much for ur reply.

is there a way to reduce these lines comming every second?

adb logcat -b kernel <- does this reduce messages?

sorry for this question:

i can also ignore theses lines? for me "failed" sounded like an real error.

05-21 17:06:14.449 E/WifiHAL (3878): Start Set Hal
05-21 17:06:14.450 D/WifiHAL (3878): error code -95 mapped to -3
05-21 17:06:14.450 E/WifiHAL (3878): Failed to register set hal start response; result = -3
05-21 17:06:14.450 E/WifiHAL (3878): wifi_start_hal failed

**Comment by Exodusnick** [comment]
If this was a real bug, your WiFi would not work.
You can ignore the messages.
