### ISSUE TITLE
compile error on wsl

### ISSUE THREAD

**Issue by lentas1** [8890q/android_kernel_samsung_universal8890#10]
**
![image](https://user-images.githubusercontent.com/88710364/196028899-975caef4-ae2a-41ae-9a12-b6afd0d6ca67.png)
**

**Comment by ivanmeler** [comment]
please try to read guide on cross compiling kernels for android device before making nonsensical issues at github, you didnt even set up gcc cross compiler or wxport arch you want to compile for
