### ISSUE TITLE
network issue since june release of los 18.1

### ISSUE THREAD

**Issue by RobertoWa** [8890q/android_kernel_samsung_universal8890#2]
hello,

my system:

samsung s7 g930f
lineageos 18.1 (microg)

my issue:
network is much slower than with the older may release. while connecting to a wifi internet check takes about 5 times longer than on may release. and in generell internet connections are established slower, sometimes it fails.

cant provide log files yet. changed back to may release.

**Comment by RobertoWa** [comment]
unfortunatly i still have problems on wifi connections on ivans and microg releases since june.

my hardware:
s7 g930f
avm fritzbox cabel router 6591 firmware 7.27

it seems that ssl connections are the issue. lot of handshake failures. i can provide logs now.

for example signal messenger registration is impossible over wifi.

what is causing this since june releases while till may is working without a problem? any hint? maybe the updated wireguard?

[bugreport-heroltexx-RQ3A.210605.005-2021-06-18-21-35-23.zip](https://github.com/8890q/android_kernel_samsung_universal8890/files/6680209/bugreport-heroltexx-RQ3A.210605.005-2021-06-18-21-35-23.zip)

**Comment by RobertoWa** [comment]
i fixed my issue by using a custom kernel (latest morokernel).

but please be so kind and have a look into it why it doesnt work with ur original kernel.

**Comment by fcuzzocrea** [comment]
Only you are having this issue ¯\_(ツ)_/¯

**Comment by RobertoWa** [comment]
possibly, but who knows who won't report it.  there are also users who use lineageos, but do not use it to make calls. You will therefore not receive any feedback from them, e.g. if there is an echo problem while calling.

but a fact is, that the may-release works and only since june it wont. so what is different on june-kernel? if i got that information, i can start to search for a solution. i want to ask the manufactor of the router, but i need to know what happened to the kernel-code since june. unfortunatly u r the only one who can answer this question. :-(

and to avoid any misunderstandings, I am not accusing anyone of doing anything wrong, I just want to understand why it no longer works. may-release works, other kernel works with june-release.

**Comment by fcuzzocrea** [comment]
The difference is that the upstream android-3.18 kernel code has been merged into our kernel tree https://github.com/LineageOS/android_kernel_samsung_universal8890/commits/lineage-18.1

**Comment by RobertoWa** [comment]
thank u. u didnt change anything else by urself?

i already opened a support-ticket at manufactor and i will give them the link u posted here. i will also send the routers logfile. they have a great support-team. i hope they can help me with the information that u provided me.

thanks for ur reply.

**Comment by RobertoWa** [comment]
i made clean installs with all june releases, only with moro kernel i have no wifi issue. from my last clean install based on los 18.1 microg release from 23. june i catched the logfile data short after install.

i am waiting for manufactor avm response.

log after reboot and switching wifi off and on:

[logcat_full_boot_process_clean_install.txt](https://github.com/8890q/android_kernel_samsung_universal8890/files/6722087/logcat_full_boot_process_clean_install.txt)

log while using browser visiting different https webpages:

[logcat_ssl_handshake_error.txt](https://github.com/8890q/android_kernel_samsung_universal8890/files/6722088/logcat_ssl_handshake_error.txt)

**Comment by RobertoWa** [comment]
update: finally the manufactor of my router fixed my issue today with a new firmware-update. now everything is working fine again. thx anyway.
