### ISSUE TITLE
icons positioning on home screen not correct

### ISSUE THREAD

**Issue by townkat** [8890q/android_kernel_samsung_universal8890#8]
icons positioning on home screen is not correct, there is a space at the bottom like for on screen navigation buttons but i do not have those enabled, i made a screenshoot, i will atach it

device: g930f, lineage 19.1

![Screenshot_20220722-050218_Trebuchet](https://user-images.githubusercontent.com/35047887/183249275-03e9cbfe-ae1f-42fe-80e0-89ea4f0bec95.png)

**Comment by ivanmeler** [comment]
not a kernel issue, this is not a device specific issue either as it affects all devices on android 12 without software buttons, cant do anything regarding that device source wise myself

**Comment by townkat** [comment]
thanks alot for answering, sorry if i posted in the wrong place, i folowed the link in the first post of lineage 19.1 rom

so, all android 12 devices have this bug? omg, so there are no officiall android 12 devices with soft buttons i guess, unbelivable

thank you so much

**Comment by ivanmeler** [comment]
Unfortunately yeah, i mean oems can implement custom launcher but launcher in lineage is based on aosp one.
I mean its possible to fix it in lineageos itself but im not aware of any official 19.1 device with hw keys like s7 that would be affected by this
